name: ReplyWith
main: NamelessLeaf\ReplyWith\Main
version: "1.0"
api: 3.0.0+ALPHA9
author: NamelessLeaf
commands:
  rw:
    description: Main ReplyWith Command
    default: true
    permission: sw.command
permissions:
  rw.command.setcommand:
    description: Set The Trigger Command
    default: op
  rw.setmessage:
    description: Set The ReplyWith Reply
    default: true
  re.reply:
    description: ReplyWith Reply Command 
    default: op
